# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Element-wise Soft Thresholding Function for Matrix
#' @description Soft-thresholding function for a matrix which is the solution of
#' \deqn{\argmin_Y ||Y-X||_2^2/2+\lambda ||Y||_1.}
#' @param \code{X}, a Matrix
#' @param \code{lambda}, a scalar
#' @return Matrix after threholding
#' @export
soft <- function(X, lambda = 0) {
    .Call(`_TestSQR_soft`, X, lambda)
}

#' @title standard Lasso estimator of the projection matrix
#' @description ADMM algorithm for high dimensional projection matrix with lasso
#' \deqn{\argmin_W tr(\frac{1}{2}W^{\top}\Sigma_z W-\Sigma_{zx}^{\top}W)+\lambda ||W||_1.}
#' @param \code{Z}, a \eqn{n*p_z} input data matrix
#' @param \code{covzx}, a \eqn{p_z*p_x} covariance matrix between \code{Z} and \code{X}.
#' @param \code{err_abs}, the absolute tolerance precision used to stop the convergence of ADMM.
#' @param \code{maxIter}, Maximum number of iterations. Default is 1000.
#' @param \code{lambda}, a scalar
#' @param \code{rho}, initial step parameter for ADMM.
#' @return A list with components
#' \item{Omega}{a list of sparse \eqn{p_z*p_x} matrices corresponding to lambda.}
#' \item{lambda}{the used lambda for the solution path.}
#' \item{niter}{the number of each iterations for each number of lambda.}
#' @export
projlasso <- function(Z, covzx, lambda, err_abs = 10^(-4), maxIter = 1000L, rho = 1) {
    .Call(`_TestSQR_projlasso`, Z, covzx, lambda, err_abs, maxIter, rho)
}

